name: Build Begonia Kernel via Marketplace Action


on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
      - name: fix ownership
        run: git config --global --add safe.directory /github/workspace
      - name: Build Android Kernel
        uses: lemniskett/android-kernel-actions@v1.0.1
        env:
          # This forces Git to ignore the container ownership mismatch globally
          GIT_SAFE_DIR: "true" 
        with:
          arch: arm64
          compiler: proton
          defconfig: begonia_user_defconfig
          image: Image.gz-dtb
